### ISSUE TITLE
[Prior] 프로그램 요구사항 파악

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#1]
- https://github.com/KAIST-IS521/2018-Spring/blob/master/Activities/0319.md
- 위 링크에 올라온 프로그램에 대한 요구사항을 파악합니다.

**Comment by zanywhale** [comment]
- 발신자와 수신자 정보는 알 수 있더라도, 내용은 발신자와 수신자만 볼 수 있어야 함
- 메신저 클라이언트가 실행되면, 다른 클라이언트의 목록 수신, Github ID와 IP주소로 구성
- 터미널에서 사용자 입력을 받으며, 이 인터페이스를 설계해야 함
- 앱은 메시지를 해독하면서 네크워크의 다른 클라이언트에게 메시지 중계를 맡아야 함
- C/C++만을 사용해야 하며, Docker를 이용해서 네트워크 구성을 해야함

+ 3월 26일까지 Prototype은 나와야 함.

**Comment by cnj8160** [comment]
사진이나 음성파일도 전송이 가능하면 추가점수....하지만 ㅜㅜ

**Comment by cnj8160** [comment]
- 발표 : team presentation directory에 "onion"이라는 branch를 생성하고 발표자료 작성
            발표 주제는 "청중들에게 우리의 채팅 프로그램을 광고" 하는 것

- 채점기준 
   1. Milestone이 잘 구성되어있는가? 구체적인가?
   2. 각 프로토콜 또는 메시지 형식이 명확하게 디자인되었는가?
   3. 인터페이스가 직관적이고 사용하기 편리한가?
   4. (Extra) 어떤 종류의 format을 전송 할 수 있는가? 예를들어, 사진 또는 음성 파일...

**Comment by cnj8160** [comment]
- 26일(월)에 우리의 프로젝트 진행 상황을 아래 기준으로 체크한다고 합니다
 1. Github를 이용하여 제작하고 있는가?
 2. 실행 가능한 프로토타입을 제작하였는가?
 3. 프로그램을 더 향상시키기 위해 노력하고 있는가?
 4. 지금까지 합당한 노력을 기울였나?

4번은 제가 이해한 바로는 저런 의미인데 나중에 한번씩 확인 해주세요 ㅎㅎ

**Comment by 2dvorak** [comment]
광고 즉 selling 이니깐 맨 처음 프레젠테이션처럼 우리 메신저를 매력적으로 보이게 할 방법?
체크포인트는 3.프로그램 향상을 위한 노력이 가장 중요할 듯 하네요. 어느 정도 틀이 나오고 나서부터는 어떻게 하면 발전시킬 수 있을지도 함께 고민해 봐야겠네요

**Comment by zanywhale** [comment]
아직도 고민인 부분 중 하나인데 서버를 둘까 말까에 대한 것과 Messenger에서 대화 내용을 어떻게 저장하고 보여줄지에 대한 내용인데, 요구사항에는 그런 내용이 따로 적혀있지 않으니 Protocol이긴 한데 그래도 최대한 요구사항에 맞춰보려고 Comment남겨봅니다.

**Comment by zanywhale** [comment]
일단 어느 정도 요구사항이 다 파악됐다고 판단됩니다.
만약 부족한 부분이 있다면 해당 이슈를 Reopen 부탁드립니다.
해당 이슈를 닫도록 하겠습니다.
