### ISSUE TITLE
[Presentation] PITCHME.md

### ISSUE THREAD

**Issue by 2dvorak** [KAIST-IS521/2018s-onion-team3#10]
PITCHME.md를 추가하도록 하겠습니다.

**Comment by zanywhale** [comment]
확인했습니다.

**Comment by cnj8160** [comment]
지난번 발표자료에 교수님께서 "제목이 조금 더 구체적이었으면 좋겠다"라는 코멘트를 해주셨기 때문에
이번엔 팀명 HER 말고 좀 더 신박하고 구체적인 제목을 생각해봐야 할것 같습니다!

**Comment by zanywhale** [comment]
그렇다면 제목에는 어떤 프리젠테이션인지 자세히 쓰고, HER과 Team member에 대한 내용을 작게 아래 쓰는게 어떨까요. 아래 ㅁㅁ에 5줄이 들어갈 분량으로!?

```
제목

ㅁㅁ
ㅁㅁ
```

**Comment by 2dvorak** [comment]
그럼 IS521 .. 제목을 먼저 쓰고 아래에 팀이름, 팀멤버를 하겠습니다

**Comment by 2dvorak** [comment]
aa5ab4f 정도로 마무리하고 이슈 닫겠습니다.
