### ISSUE TITLE
[Program] pgpcrypto.* file

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#14]
Issue #6 branch에서 작업이 완료되어 PR되었습니다.
```
git fetch origin master
git pull origin master
```
를 통해 동기화 후, 작업해 주세요.

- pgpcrypto.* 파일에 Enc, Dec 부분을 구현해주세요.
- 암호화, 복호화는 각각 PGP를 이용하며, passPhrase는 keymanager에서 사용되고 있기 때문에, 연결하는 것은 제가 추후에 작업하며 연결하도록 하겠습니다. passPhrase는 입력받아 사용하도록 먼저 작업하세요.

**Comment by cnj8160** [comment]
확인했습니다!

**Comment by zanywhale** [comment]
https://gnupg.org/software/libraries.html
여기서 GPGME라는 프로그램을 참고해 보세요! 이것으로 하면 될 듯 싶습니다.

**Comment by zanywhale** [comment]
진행사항에 대한 내용을 댓글로 남겨주세요!

**Comment by cnj8160** [comment]
일단 현재까지의 내용을 issue14-pgpcrypto 브렌치에 올려놨습니다.
했다고 하기도 부끄러울 정도로 아주아주 간단한 내용이지만,
위의 "Not using file" 부분은 system(터미널 명령어) 함수 이용해서 터미널 상에서 메시지를 암호화 하는 방법인데 문제는 이렇게 만들어진 암호화 문자열을 변수에 바로 저장할 수 있는지가 의문입니다.
암호문이 변수에 저장이 되어야 이를 이용해 복호화가 가능한데 이 부분 구현에서 막혀있는 상태입니다.

아래의 "Using file" 부분은 우리가 실습때 했던것처럼 메세지 파일, 암호화 파일, 복호화 파일을 매번 생성해주는 방법인데 굉장히 불편한 방법이어서 적절치 않을 것 같습니다.

**Comment by zanywhale** [comment]
저도 그 부분에서 좀 고민이 많네요ㅠㅠ
같이 고민해봐야 할 내용인 듯 싶습니다.

**Comment by cnj8160** [comment]
일단 message가 변수 형태로 오기 때문에 굳이 message.txt 파일을 생성할 필요는 없어서
암호화 파일, 복호화 파일 두 가지만 생성되도록 바꿨습니다.
메세지를 생성할 때마다 덮어쓸건지 계속 물어보는 문제도 해결했는데
복호화시에 변수 passPhrase를 적용시킬 방법이 없어서 일일이 비밀번호를 입력해줘야 하네요
한번 입력된 passPhrase를 이용해서 자동으로 복호화를 시켜줘야 하는데 이 부분 생각해봐야겠네요 ㅜㅜ

**Comment by zanywhale** [comment]
오늘 할 내용입니다. 허허
