### ISSUE TITLE
[Program] sockserver.* file

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#15]
Issue #6 branch에서 작업이 완료되어 PR되었습니다.
```
git fetch origin master
git pull origin master
```
를 통해 동기화 후, 작업해 주세요.

Thread로 Background Server구성해주시면 됩니다.
그리고 쓰레드로 전환..?!

- sockserver.* file 작업 부탁드립니다.
- messenger.*에 있는 Loop도 같이 건드리셔야 할겁니다.
- 추가적으로 Send에도 socket 및 thread를 적용해야 하긴 하는데, 그건 본 작업 이후에 하도록 하겠습니다.

**Comment by 2dvorak** [comment]
넵 알겠습니다!
가즈아아아아아 🏃💨💨💨  ⏩⏩⏩

**Comment by 2dvorak** [comment]
port는 임의의 고정된 번호를 써도 될지? 혹시 다른 어플리케이션과 겹친다면..? 그를 방지하기 위해 동적으로 포트번호를 할당한다면, 맨 처음 접속시 다른 노드들에게 포트 번호에 대한 정보도 보내줘야되는 불편함이..?

**Comment by 2dvorak** [comment]
키(노드 정보) 송/수신 쓰레드와 메시지 송/수신 쓰레드를 생성하기 이전에, main() 함수 등에서 사용자 입/출력 쓰레드를 먼저 돌려놓으면, 나중에 쓰레드를 만드는 등의 동작에서 에러가 나거나 하면 출력하거나 그에 대한 사용자 입력을 받을 수도 있을 것 같네요. 15이슈와는 상관없지만 일단 여기에 적어놓습니당.

**Comment by zanywhale** [comment]
1. 포트는 고정으로 사용하십시오.
2. 일단 확인했습니다!

**Comment by zanywhale** [comment]
진행사항에 대한 내용들을 댓글로 남겨주세요!

**Comment by 2dvorak** [comment]
소켓으로 받는 부분은 어느정도 구현이 완료되었는데, 보내는 부분도 sockserver 쪽에서 처리해줘야 할 듯하여 sockserver를 sockthread로 바꾸었습니다. 이후 보내는 부분 구현을 맡아주신 @skyshiri 님께서 내용을 추가해주시기로 했습니다.

**Comment by 2dvorak** [comment]
@skyshiri 님께서 send부분 커밋해주셨고 이후에 제가 좀 수정했습니당

**Comment by 2dvorak** [comment]
또 사용자의 입/출력을 받는 쓰레드(UI thread)를 만들어 보았습니다. 그래서 자기 자신에게 send/recv 하게 해서 출력이 되게 해 보았습니다. 상당히 보기 좋지 않지만 돌아가긴 합니다. 해당 쓰레드는 messenger 클래스에 추가했습니다.
또 메시지 큐를 글로벌하게 사용하기 위해 common.h에 extern으로 선언해준다거나, message 클래스에 큐 관련 함수를 추가한다거나 등의 간단한 수정을 했습니다.
