### ISSUE TITLE
[Program] message.* file

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#16]
Issue #6 branch에서 작업이 완료되어 PR되었습니다.
```
git fetch origin master
git pull origin master
```
를 통해 동기화 후, 작업해 주세요.

message.cpp&h파일에 SendMessage(), RecvMessage() 함수가 있습니다.
그 중, SendMessage()는 SocketClient역할을 하는데, 이 Client 부분을 코딩해주시면 되겠습니다!

**Comment by skyshiri** [comment]
확인했습니다. 내일 오전에 팀장님 시간되실 때 자세히 문의 하겠습니다.

**Comment by 2dvorak** [comment]
저도 같이 갈래요..

**Comment by skyshiri** [comment]
헐, 승엽님이 이러시면 아니 됩니다.  실력자는 자력갱생하셔야죠.

**Comment by 2dvorak** [comment]
한정된 리소스를 독점하시면 안됩니다.
지금 혼자 쓰레드 c++ 만들어 보면서 공부하고 있어요..

**Comment by skyshiri** [comment]
네, 그렇군요. 열심히 프로그래밍하는 줄 알았는데, 공부하고 계셨네요.

**Comment by 2dvorak** [comment]
네 그리고 방금 첫 C++ 쓰레드 만드는데 성공했습니다.

**Comment by zanywhale** [comment]
화이팅이십니당^^

**Comment by zanywhale** [comment]
@2dvorak 님이 만들고 계신 부분은 send를 맡고있는 thread에서 queue를 확인하고 계속 보내주는 식입니다.
세진님이 작성해 주실 부분은 queue와 mutex를 사용해서 안전하게 send thread가 queue에 있는 내용을 send할 수 있도록 작성하는 것을 목표로합니다!

아무레도 @2dvorak 님과 협업이 어느 정도 필요 할 것 같으니, 같은 랩실에서 알콩달콩...♠

**Comment by skyshiri** [comment]
승엽님이 여기 있다는 게 천만 다행입니다. 👍 😄  난 코딩은 아닌가봐요. ㅠㅠ 😢

**Comment by 2dvorak** [comment]
이 부분은 #15 에서 함께 다루었습니다. 아마 Message 클래스는 프로토콜에 맞춰서 보낼 메시지를 어셈블하는데 사용될 것 같습니다.

**Comment by zanywhale** [comment]
이 부분은 아무래도 @skyshiri 님이 C++ STL을 바로 쓰시기가 힘들 것 같습니다.ㅠㅠ
제가 합류해서 돕도록 하겠습니다.

**Comment by zanywhale** [comment]
본 이슈는 Prototype 만들기 이슈에 합치도록 하겠습니다.
