### ISSUE TITLE
[Program] Make Prototype

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#19]
이전 이슈에서 다루었던 모든 프로그래밍이 완료되면 동작 가능한 프로토타입을 만들 예정에 있습니다.
현재 빈 깡통으로 만들어드린 Class들은 전부 제대로 동작하는 것을 확인했고, @2dvorak 님과 @skyshiri 님이 맡아주고 계시는 Socket Thread 작업이 거의 끝나간다고 말씀해주셨습니다.

위 Socket 작업과 @zanywhale의 Docker작업 그리고 @cnj8160 님의 gpg 관련 암호작업이 끝나면 앞으로 있을 일정에 대해서 말씀드리드록 하겠습니다.

- Socket Thread 작업이 완료되는대로 Docker에 넣어 네트워크 세팅을 마쳤을 때 제대로 메시지가 전송되는지 확인 할 예정입니다.

- 메시지가 전송된다면 gpg를 이용해서 Encrypt와 Decrypt와 연동해 1:1로 암호화 대화가 가능하도록 만들 예정입니다. 이와 더불어 GithubID와 Key list관리에 대한 부분을 마칠 예정입니다.

- 최종적으로 UI구성으로 Beta version program이 완성됩니다.

Prototype이 완성되면 gpg쪽 코딩에 대한 문제(라이브러리) 그리고 #9 메시지 프로토콜 설계 부분에서 추가적으로 제시된 의견들을 추합하여 필요한 기능들을 추가할 예정입니다.

기능에 대한 추가는 코딩이 어느 정도 되시는 분들과 함께 진행하고, 코딩이 미숙하신 분께서는 README.md와 Presentation준비를 해주시면 되겠습니다.

위와 같이 일을 분배해서 진행하면 일단 최종 프로토타입은 3월 23일(금) 내로 만들어 질 예정이고, 토, 일에 프로그램 보강, Presentation 및 Protocol 설계에 대한 문서(?)를 정리하고 최종적으로 수요일에 발표하면 되겠습니다.

Prototype에 관련된 질문들은 댓글로 남겨주시고,
앞으로의 진행사항에서 궁금하신점이나, 혹은 회의를 해야 할 점, 이상한 점들은 Issue에 [Question] 으로 새로 만들고 label Type: Help wanted를 달아 올려주시면 최대한 빠른 반영 노력하겠습니다.

감삼다!

**Comment by 2dvorak** [comment]
가즈아.. 👦🔫

**Comment by skyshiri** [comment]
잘 알겠습니다.

**Comment by cnj8160** [comment]
확인했습니다!

**Comment by zanywhale** [comment]
RecvKey, SendKey부분이 완료되어서 ShowList부분을 추가했고, 이제 Listing되어있는 상대의 IP를 받아 통신하게 하는 것을 완성 할 예정이고,
이 부분이 다 되면 바로 암호화 적용 할 예정입니다. 암호화 적용이 완료되면 Selective Path를 적용 할 예정입니다.

**Comment by zanywhale** [comment]
Message 주고받기까지 끝냈고, 암호화만 하면 될 것 같습니다~

**Comment by zanywhale** [comment]
암호화와 UI구성이 얼추 마무리되면 프로토타입은 완성됐다고 보고 넘어가도록 하겠습니다.
Final 프로그래밍에 랜덤 경로 선택을 넣어서 마무리하면 될 것 같습니다.

**Comment by 2dvorak** [comment]
#31 #32 merge한 이후 발생한 conflict(시맨틱 차이로 인한)를 해결하였습니다. 해당 작업은 master 브랜치에서 했습니다. 지금은 어느 정도 돌아가지만, 채팅방을 들락거리다 보면 펑 터집니다 하하
채팅방 목록이나, 채팅방 내에서 나가고 싶으면 ESC를 누르시면 됩니다. 안나가지면 사용자의 키보드에서 ESC에 대한 ncurses의 getch() 리턴값이 27이 아닌겁니다. 설마 키보드마다 다르면 굉장히 골치아플듯

**Comment by zanywhale** [comment]
@2dvorak 대화할때 제 편에서 상대방이 메시지를 보냈을 때, UI가 깨집니다. 확인해주세요!
