### ISSUE TITLE
[Program] JSON Parser

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#22]
오픈소스를 들구와도 상관없습니다.

**Comment by 2dvorak** [comment]
저두 상관없습니다 😄 
$ git reset --hard 1b04fae26fcd9434119e95f70da398efc50bfa22
$ git push -f origin master

**Comment by zanywhale** [comment]
이게 완성되어야 프로토콜이 완성되고
프로토콜이 완성 되어야 키 교환이 완성되고
키 교환이 완성되어야 메시지 교환이 완성되고
키, 메시지 교환이 완성되어야 UI를 만들 수 있고
UI를 갖춰놔야 Prototype이 완성되고
프로토 타입이 완성되어야 프리젠테이션을 만들 수 있고

뭐 그렇습니다.

부담을 주려고 그러는건 아니에요 ㅎㅎ

**Comment by 2dvorak** [comment]
자손 파싱하는 로직을 집어넣었습니다. Message 클래스에서 하면 아주 적절할 듯 해서 Message의 생성자와 메소드에 자손 관련 로직들을 넣었습니다. Message 클래스는 send/recv에서 유용하게 사용될 듯 합니다.
그말인즉슨 아직 Message 클래스를 사용하는 부분은 없습니다. 만들기만 했어요.

**Comment by zanywhale** [comment]
괜찮습니다. 그 부분들은 제가 템플릿 화 해놓은 것에서 없던 내용이니 어쩔 수 없죠
최종적으로 작업 완료되면 제가 클래스화해놓겠습니다. ^_^
고생하시네욥

**Comment by 2dvorak** [comment]
자손에 들어가는 필드가 4개입니다. int, bool, string, string 인데요 키 프로토콜과 메시지 프로토콜을 함께 처리하기 위한 방법을 고민해본 결과인데요.

| Type      | Msg Protocol                                   | Key Protocol    | 
|----------|----------------------------------------|------------------|
|int          |if ID = 1, Msg Protocol                       |if ID = 0, Key Protocol
|bool       |isLast: am I the destination of this msg?|on/off: is Key Protocol sender logging in or off?|
|string     |IP: if(isLast) sender IP; else next node IP|IP: Key Protocol sender's IP|
|string     |content: message content                      |Github ID/PUBKEY|

**Comment by 2dvorak** [comment]
send/recv에서 지금은 큐에 저장된 메시지 스트링을 보내고 읽는데요. 지금부터는 큐에 메시지와 기타 헤더를 jsonify한 JSON 스트링을 저장하고 그걸 send/recv 시키게 하겠습니다.

**Comment by zanywhale** [comment]
괜찮아보입니다. 저는 이거 말고 따로 빠진게 없어 보이는데 어떻게 생각하세요?
@cnj8160 @skyshiri

**Comment by zanywhale** [comment]
넵 잘 알겠습니다. 그렇게까지 해주시면 감사하죠 ㅎㅎ

**Comment by zanywhale** [comment]
ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
