### ISSUE TITLE
[Program] Socket refactoring / UI 구성

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#23]
소켓을 만들어주셨으니, 이를 가지고 UI 구성해서 UI쓰레드까지 넣도록 하겠습니다.
완성 목표는 3월 22일목요일입니다.

**Comment by zanywhale** [comment]
리팩토링이라 말하긴 애매하고, Clean up을 했습니다.
전반적인 수정은 끝났고 UI 쓰레드 틀만 잡아놨습니다.

**Comment by 2dvorak** [comment]
충돌을 방지하기 위해 한번 master로 merge했습니다~ #24

**Comment by zanywhale** [comment]
일단 UI 쓰레드까지 완성 했고, 나머지는 부가적으로 추가하면 될 내용이라 큼직한 내용도 끝났고, 이슈의 주된 내용이었다 Socket Refactoring이 끝났기 때문에 해당 Issue는 닫도록 하겠습니다.

**Comment by 2dvorak** [comment]
누가 UI 쓰레드를 닫았는가.
양파링 가즈아
