### ISSUE TITLE
[Program] send/recv 로직 수정

### ISSUE THREAD

**Issue by 2dvorak** [KAIST-IS521/2018s-onion-team3#26]
JSON 관련 구현이 완료되었기 때문에 send/recv에서 해당 구현을 이용하도록 하겠습니다.
아직은 자기 자신에게 메시지를 보내는 게 다지만, 이제는 JSON을 한번 거치게 됩니다.

**Comment by zanywhale** [comment]
확인했습니다.^_^

**Comment by 2dvorak** [comment]
send/recv는 지금처럼 그대로 큐에서 꺼내서 보냅니다. 대신 화면에 출력하거나 사용자 입력 받는 쪽에서 JSON을 처리하도록 했습니다. JSON 처리는 Message 클래스를 이용합니다.

**Comment by zanywhale** [comment]
확인했습니다.
흠.. 메시지들을 관리할때 그냥 unordered_map으로 포인팅해서 string으로 관리하면 프로그램 실행중에만 메시지 볼 수 있게 만들 수 있겠네열 파일 써도되긴하는데, 컨셉으로 잡아도되구요

**Comment by 2dvorak** [comment]
또한 여기 이슈와는 상관없지만 UI 부분을 좀 만져보았습니다.. ncurses 라이브러리를 사용해서 화면을 제어할 수 있게 해 보았습니다. 저번에 만든 UI는 출력이 좀 꼬였는데, 지금은 봐줄만합니다.
남은 것은 암호화, 그리고 프로토콜을 이해하게 해야됩니다. 그리고 채팅방 목록?등을 관리할 수 있게끔 보낸이를 구분할 수 있어야 합니다.

**Comment by zanywhale** [comment]
그 부분은 github ID를 Key로해서 unordered_map으로 관리하게 하는게 좋을 것 같네요.
ncurses라이브러리는 쓰려고 저번에 Dockerfile에 추가해두긴 했슴다.
이제 프로토타입 완성시키고 PGP만 입히면 되긴 하겠네요
