### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by sangkilc** [KAIST-IS521/2018s-onion-team3#27]
Seems like a very active group. You don't want to have a gitpitch file mixed with the project though. Read the project document again. I explicitly said that you should create a branch in your presentation repo, not here.

**Comment by zanywhale** [comment]
좋은 지적해주신 코맨트 감사합니다. : )

이번 Comment에 대한 이슈 처리는 @cnj8160 님이 맡아서 해결 부탁드립니다.
```
- Presentation Repo에 onion Branch만들고, 필요한 내용 정리 부탁드립니다.
- 현재 올라가있는 assert, PITCHME.md관련 모든 자료를 issue27-delete 라는 브랜치를 생성해서 제거하고 PR부탁드려요!
```

**Comment by cnj8160** [comment]
미션 완료하였습니다!
issue27-delete 브렌치를 만들어서 assets 폴더와 PITCHME.md, PITCHME.yaml 파일을 삭제하였고 PR 날렸습니다.
presentation repo에 onion 브렌치를 생성하여 위에서 삭제한 폴더 및 파일들은 붙여넣어주었고 필요 없는 내용들은 삭제하였습니다.
