### ISSUE TITLE
[Work] 프로그램 설계에 따른 역할 분배

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#3]
- 프로그램 설계가 완료되면 해당 이슈가 시작됩니다.
- 해당 이슈는 프로그램 설계에 제시된 컴포넌트들을 각각 배분하도록 합니다.

**Comment by zanywhale** [comment]
@zanywhale : 프로그램 설계, 클래스 설계
@skyshiri : 메시지 관련 클래스 코딩
@2dvorak : 프로토콜 코딩
@cnj8160 : 암, 복호화 코딩

**Comment by zanywhale** [comment]
일단 위와 같은 역할 분배가 완료되었고, 해당 역할에서 추가적인 사항들이 발생 시 역할에 추가하도록 하겠습니다.
본 Issue는 닫도록 하겠습니다.

**Comment by 2dvorak** [comment]
@2dvorak: 프로토콜 코딩(ACK, 노드 추가/탐색/종료 등에 대한 규약)
