### ISSUE TITLE
[Program] PGP를 이용한 encrypt 적용

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#34]
Prototype에 현재 PGP를 이용한 Encrypt, Random path, UI부분이 남았습니다.

본 이슈에서는 PGP를 이용한 Encrypt적용을 진행하도록 하겠습니다.

**Comment by zanywhale** [comment]
개발에 편의를 위해 PGP key를 임시로 4개 생성하여 테스트하겠습니다.
해당 Key는 public key와 private key를 전부 올리겠습니다. 
비밀번호는 `PGP`로 암호화해서 공유드리겠습니다.

**Comment by zanywhale** [comment]
거의 다 마무리 됐고,
gpgme_set_passphrase_cb() 부분까지만 해결하면 될 것 같습니다.

**Comment by zanywhale** [comment]
오늘 하루종일 GPGME 가지고 씨름했는데요. 
굳이  GPGME를 써야 할 필요성을 못느낍니다. 복잡할 뿐 더러, 가장 중요한건 속도가 심각하게
너~~~~~~~~무느립니다.

그냥 조금 복잡하더라도, 쉘통신을 통해 encrypt, decrypt를 하는게 나아 보입니다.

**Comment by zanywhale** [comment]
오늘 하루종일 GPGME가지고 씨름했는데, 다 날렸습니다 ㅠㅠ
내일 popen으로 작업 마무리 하면 될 것 같습니다.

**Comment by sangkilc** [comment]
This seems like an important design decision. I expect you to discuss this issue in the presentation.

**Comment by zanywhale** [comment]
@sangkilc Thank you for your very good advice!!!

**Comment by 2dvorak** [comment]
pgpmanager에서 공개키/비밀키 import, 암복호화, 비밀번호 관리 등을 구현하도록 하겠습니다.

**Comment by zanywhale** [comment]
@2dvorak 넵 그렇게해주세요. 추가되는대로 이어서 작업받아 시작하겠습니다. 드디어 Sign을 고쳐써요

**Comment by 2dvorak** [comment]
TODO
```
Note that the Dockerfile would also have to transfer the user's private key into the
docker container. Assume that the user's private key file exists in the same directory
with the Dockerfile. When the onion messenger starts, it should receive the
passphrase of the user's PGP key from the terminal (i.e. stdin).
```
요구사항에 따르면 .key는 Dockerfile과 같은 폴더에 있고, 도커가 실행되며 onionMessenger executable과 같은 폴더에 복사가 되어야 합니다.

또한 .pub 파일에 대한 요구사항이 없기 때문에, .key를 가지고 .pub를 만들어내어 봐야겠습니다.

비밀번호를 받는 방식은 stdin을 말씀하고 계시지만, argument도 터미널이라 볼 수 있으니..괜찮으려나요?아니면 로그인 화면을 만드는 것도 **상-당히** 보기 좋을 것 같습니당당당

**Comment by zanywhale** [comment]
로그인 화면을 만드는것도 좋아보입니다.ㅋ_ㅋ
그러면 일단 맡아주시기로했던 GPG_enc,dec, key_import 까지 해주시고 시간 남으시면 private key로 pub export랑 로그인 화면 만드는거 해주시면 좋을 것 같습니다.ㅋ_ㅋ

**Comment by 2dvorak** [comment]
🕛 🕒 🕕 🕘 아유 남는게 시간이죠^~^... 😇

**Comment by zanywhale** [comment]
암호화는 그냥 진행하고, Dec때만 파일로 떨궈서 진행합시다
