### ISSUE TITLE
[Work] README.md 작업

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#35]
프로그램 상세 설명 및 Usage, abstract등 필요한 내용을 채워넣을 작업이 필요합니다.

**Comment by cnj8160** [comment]
추후에 인사이트 작업해서 추가하겠습니다!

**Comment by zanywhale** [comment]
@skyshiri 이 작업은 SkyShiri님이 맡아주시길 바랍니다.
TA께서 지적하신 부분들 추가해 주시고, 더 추가되거나 작성되어야 할 내용이 있다면
@2dvorak @cnj8160 @zanywhale 이 댓글로 주기적으로 추가 요청 드리도록 하겠습니다.
추가 요청이 들어오는 것들은 모두 @skyshiri 님이 작업해주셔야 합니다!
본 작업은 issue35-readme branch에서 부탁드립니다.^_^

**Comment by skyshiri** [comment]
네, 잘 알겠습니다.

**Comment by zanywhale** [comment]
설치되어야 하는 패키지는 다음과 같습니다.
qt4-qmake, libncurses-dev, make

**Comment by zanywhale** [comment]
지금까지 되어 있는 내용 피드백을 조금 드리자면 Installation같은 경우 명령어만 나열하는게 좋아 보입니다. 그리고 앞에는 번호보다는 어차피 시간순서대로 나열되기 때문에 $으로 쉘 명령어라는걸 알려주는게 조금 더 낫습니다! 그리고 루트권한으로 실행된다는 것을 표현하자면 $보다는 #이 낫구요. 이런식으로 하면 됩니다.
```
$ cd onionMessenger
$ make
$ cd ..
# ./AutoDocker.sh
# ./startMessenger.sh
[Docker]
# ./setup.sh
# cd onionMessenger
# ./onionMessenger
```
대강 이렇게 Installation과 Usage를 쓰시면 될 것 같고 위에는 제가 할 때 이런식으로 하기 때문에.. 혹시 다른 컴퓨터에서는 안될 수 있습니다. 그러니 직접 명령어 쳐보시고 안되는 부분이나 조금 이상한 부분은 댓글 달아서 알려주세요

**Comment by 2dvorak** [comment]
와 이거 제가 오프라인에서 말씀드린거랑 상당히 유사합니다 @skyshiri  어때요

**Comment by skyshiri** [comment]
잘 알겠습니다.

**Comment by zanywhale** [comment]
프로토콜 디자인에 type을 전부 string으로 써주셔야 할 것 같습니다. JSON이라는 것도 명시해 주어야 할 듯 싶고, 프로토콜 디자인중 일부 예시를 드는 것도 좋을 것 같습니다.
Ex) {"id":"0", "bullian":1, ~~~~ } 이런식으루요

**Comment by zanywhale** [comment]
그리고 @skyshiri 님 직접 한번 써보셔야 Usage랑 Installation을 체크해볼 수 있을 듯 싶네요 ㅎ_ㅎ
지금 바뀐것도 있어서요!

**Comment by zanywhale** [comment]
추가적으로 Usage에 사용 설명에 대한 내용도 들어가야 할 것 같습니다. 들어가서 ID, PW입력하게하고 Talk들어갔을때 스크롤로 선택, 엔터로 클릭 그리고 Talk에서 빠져나오는 키는 ESC 이런 내용들이요

**Comment by skyshiri** [comment]
일단 Protocol design과 Onionrouting은 승엽님 도움을 받아 작성을 했는데, 다들 보시고 의견 좀 주세요.

**Comment by cnj8160** [comment]
example에 실제 동작화면을 캡쳐해서 집어넣는건 어떨까요?

**Comment by 2dvorak** [comment]
@cnj8160 그렇게 할 예정입니당 다만 지금은 UI가 완성이 아니라, 완성되고 찍는게 좋을거같습니다

**Comment by zanywhale** [comment]
Review!
```
- 우리 제품 이름이 가장 위에 들어가는게 좋지 않을까 생각하는데 어떻게 생각하시나요?
- Abstract에 조금 더 내용이 들어가야 할 것 같습니다. (같이 생각해봐요)
- Protocol Design에 뒤에 Environment에 쓰긴 했어도 JSON을 사용했다는 것을 간단하게 넣어 주면 좋을 것 같습니다. (예시와 함께)
- OnionRouting에 그림 굉장히 잘 그렸네요! 추가적인 설명과, 랜덤인지 아닌지, 몇 명까지 체이닝이 되는지에 대한 설명 즉 Detail이 필요해 보입니다.
- 패키지 설치 이후 라고 적혀 있는 부분 git clone을 했으면 cd 2018s-onion-team3가 나와야 할 것 같은데 없네요. cd ..은 없어도 될 것 같은데요?
- Usages에 ./onionMessenger만 쓰면 되고 현재 argv쓸 필요 없습니다. 프로그램을 실행시켜봐주세요.
- Usages에 실제 사용법이 추가되야 할 것 같습니다. githubID 입력, Passphrase 입력 후, 1, 2 ,3번이 각각 무슨기능인지, 2번 눌렀을 때 방향키와 엔터로 사용해야 하며 ESC로 빠져나온다는 설명이 필요해보입니다.(프로그램 조작법)
- Example은 사진으로 대체하기로 한거 확인했습니다.
- 현재는 testkey로 전부 진행되었지만, 자신의 private.key로 진행하기 위해서는 [ID].key파일과 [ID].pub파일이 필요하다는 것을 명시해 주어야 할 것 같습니다. key파일은 디렉토리를 마운트시켜 공유 할 예정이라, testkey에 개인의 키를 넣어 주어야 한다는 것을 명시해야 합니다.
```

확인하고 반영 부탁드릴게요.

**Comment by zanywhale** [comment]
추가로 Protocol Design에서 
```
boolean이 아니고 bollian
Gtihub id가 아니라 githubID
contents가 아니라 content
Message Protocol에서 sendIP 송신자 IP(마지막 메시지)
```
입니다 확인해주세요.

**Comment by zanywhale** [comment]
- JSON에서 큰따움표 지금 유니코드로 들어가 있는데 " 요놈으로 변경해주세요!
- 메시지 전송 경로는 최대 5단계로 random 지정 > 이거 random Path로 전송 이런식으로 random으로 뭘 지정한다는지 확실하게 써주면 좋을 것 같아요!

**Comment by zanywhale** [comment]
~$_ : 현재 사용자의 명령 대기
~#_ : 슈퍼 유저의 명령 대기
위 부분 ~$_ 에서 ~, _는 왜 들어간건가요?
지금 설명한 부분에서는 $나 #앞에 아무것도 없기 때문에 그냥 쓰셔도 될 것 같습니다. 
```
$ : 일반 사용자의 명령 대기
# : 슈퍼 유저의 명령 대기
```
그리고 현재 사용자라기보단 일반 사용자로 변경하는 게 좋을 듯 싶습니다.

**Comment by skyshiri** [comment]
팀장님, 너무 부지런하십니다. 팀장님의 패션을 교수님이 충분히 아셔야 될텐데요.
반영하여 수정하겠습니다.

**Comment by zanywhale** [comment]
ㅋㅋㅋ.. 그냥 원래 제가 좀 피곤한스타일이리 요구사항이많을뿐입니다.
팀원분들이 고생하실뿐이죠 ㅠ_ㅠ

**Comment by zanywhale** [comment]
$ ./AutoDocker.sh
요놈 루트로 실행하셔야될껄요?

**Comment by zanywhale** [comment]
PR받았고 변경 안된 점과 수정 내용 정리해드립니다.
```
- JSON형식으로 만들어서 전송 Example에서 "sendIP":""을 넣어주셔야 합니다! githubID도 마찬가지구용
- 제가 잘못 말씀드렸는데 그림에서 D에 senderIP에 192가 아니라 172로 써주세요 ㅠㅠ
- 프로그램 파일 설치에서 ./AutoDocker.sh은 루트로 실행돼야 합니다.
```

**Comment by skyshiri** [comment]
반영하겠습니다.

**Comment by 2dvorak** [comment]
저는 AutoDocker.sh 유저 권한으로 실행시키고 있었는데요..
도커 설치할 때 sudo useradd -a -G lee docker 뭐 이런 명령어 줬던거 같네요.

**Comment by skyshiri** [comment]
저도 유저 권한으로 실행시키면 되던데..
팀장님의 지속된 요청에 $를 #으로 변경할 수밖에 없었어요. 흑흑 ㅋㅋ

**Comment by skyshiri** [comment]
#을 다시 $로 바꾸면 되나요?

**Comment by 2dvorak** [comment]
아뇨 팀장님 말 들어야됩니다ㅠㅠ혼납니다ㅠㅠ

**Comment by zanywhale** [comment]
sudo useradd -a -G lee docker
요거하시면 상황에 따라 리붓이 필요할 때가 있습니드아@_@..

**Comment by zanywhale** [comment]
거의 다 된듯 싶습니다.
HER messenger 앞쪽에 특장점에 대한 설명을 달면 좋을 것 같습니다.

**Comment by zanywhale** [comment]
PR 받았습니다. 더 이상 추가할 내용이 없어 보이고, 추가할 내용이 있다면 그때 말씀드리겠습니다.
해당 이슈는 닫도록 하겠습니다.
