### ISSUE TITLE
[Program] Make final program

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#38]
현재 알파버전의 프로그램이 마스터 브랜치에 올라가 있습니다.
프로토 타입이라고 봐도 될 것 같습니다.

마지막으로 popen에 총력을 기울입시다.

**Comment by zanywhale** [comment]
@2dvorak 저번에 얘기했던 Queue작업 관련된 이슈를 올렸습니다. 빠진거 있으면 말해주세용

**Comment by 2dvorak** [comment]
@zanywhale 🙆‍♂️

**Comment by zanywhale** [comment]
PGP 적용 끝

**Comment by zanywhale** [comment]
거의 다 끝났네요@_@
남은 내용
```
- popen에서 파일 삭제 관련 이슈 (Mutex 걸어야 한다고 보고 있음 저는)
- Msgstr에서 vector 개인 관리
- UI 이쁘게 수정
```
이정도 남았나요?

**Comment by zanywhale** [comment]
아 그리고 전 Warning을 못봐주기 때문에 Warning 다 수정할겁니다.

**Comment by zanywhale** [comment]
위에 남은 내용이던 popen에서 파일 삭제 관련 이슈는 해결 된 듯 싶습니다.@_@
동시참조라니.. 현재 도커가 -v로 마운팅되어있어서 생기는 문제입니다.@_@!흐어어엉

해결방안은 두 가지 정도 똑뿌러지는게 나오는데,
1. ./startMessenger에서 -v 옵션을 빼서 마운팅을 없애고 Dockerfile에서 파일을 복사하는 형식
2. 프로그램 내에서 ID에 해당하는 디렉토리를 생성해서 거기서 popen작업 하기

**Comment by 2dvorak** [comment]
3. rand()의 시드로 time같은 스레기 시드 쓰지 않기. micro초 단위정도는 되어야함

**Comment by 2dvorak** [comment]
-터미널 사이즈가 바뀌는 걸 탐지 못함
-기본적으로 모든 상황에서 exception을 가정하고 처리를 해주어야함. 적어도 오류 메시지 그대로 출력하지 말고 곱게 죽도록..
-경로를 거치며 메시지 길이?가 줄어드니깐 패딩을 붙여본다면?
-자기 자신도 경로에 포함시킨다면?(랜덤니스를 위해)
-지금 소켓 읽을 때 버퍼 길이가 정해져있는데, 더 긴 메시지 또는 파일이 온다면?안됨 따라서 동적으로 읽을만한 방법이 없을지 생각해볼 필요

**Comment by zanywhale** [comment]
google에서만든 log / glog쓰면 좋긴합니다.@_@!
경로거치며 길이 줄어드는 문제는 어차피 JSON이고 parsing안하는 "aaaaaaaa":"aaaaaaaaaaaaaaaaaaaaaaa"이런걸로 패딩하면 될 것 같긴 해요 보안적으로 강화!

자기자신 경로에 포함시키는거 안해봤는데 해보고 버그 없으면 추가해도 괜찮을 것 같아요~_~

소켓에서 앵간한 긴 문자는 처리해주고 있는데, (현재 테스트 결과 1000자까진 무난해 보입니다.) 근데 파일이나 더 긴 문자열이 왔다갔다 거리면 "}"를 받을 때 까지 받으면 되긴합니다~_~ 호오

**Comment by 2dvorak** [comment]
호오 그러고 보니 만약에 2000자 넘게 치려고 하면 터미널이 80*24면 입력창이 모자라겟는디요. 그런거 처리를 안해줫군용용..
근데 ctrl+shift+C 로 붙여넣기하면 그 입력이 메신저에 넘어오기 전에 터미널에서 붙여넣기를 하던디..근데 붙여넣은 메시지가 잘 입력되는거 보면, 터미널에서 한글자씩 넘겨주는건가 싶기도 하고요.
그러니깐 입력창 줄 수 길이에 제한을 주도록 해봐야겠습니다.

**Comment by 2dvorak** [comment]
입력창 줄 수 길이에 제한을 줬습니다. 9b0020b9a0cb4b8e5e8507a36fb5997e5dc28d5e

**Comment by 2dvorak** [comment]
- 소켓 길이 : "}"로 해결해볼 수 있을 것
- 특수 문자 처리 : tab은 space 4개를 더해준다 치고, \n은 애매함. 0x0a가 들어오면 send를 해버린다..
만약 줄바꿈을 어떻게 받는다 치면, 화면 크기가 고정되어 있다면, 화면 너비 만큼의 공백을 넣어줄 수 있겠지만, 그렇게 고정해서 박아놓으면 크기가 다르면 받는 쪽에서 다르게 보일 여지가 있다.
- 패딩
- 터미널 사이즈?가능하련지ㅠ

**Comment by zanywhale** [comment]
대강 프로그램은 마무리된것같아보입니다. ㅎㅎ

**Comment by 2dvorak** [comment]
Exception 핸들링?

##### UI 발전
-카톡처럼? 들어갔을 때 바로 사용자 리스트, 오른쪽으로 넘기면 대화창 리스트 그런식 ㅎㅎ..
-새로운 메시지 팝업 알림?!
##### 추가기능
-단톡방
-파일 전송
