### ISSUE TITLE
[Prior] 브랜치 및 이슈 네이밍

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#4]
- 브랜치 네이밍을 어떻게 할지 정해보로독 합시다.
- 이슈에 대한 네이밍도 일단 제가 [Work]라고 해두었는데, 어떻게 하는 것이 좋을 지 얘기해 봅시다.
- Label은 제가 임시로 다른 사이트에서 참고하여 넣어두었는데, 이견있으신분 답글 달아주세요.

**Comment by zanywhale** [comment]
개인적인 견해로는 이전에 팀 프리젠테이션 했던 것 처럼 Issue별로 나누고 싶기도 한데,
Program의 component별로 나눠야 하는게 아닌가 싶기도 해서 의견을 공유해보고자 합니다.

그리고 현재 issue naming은 [Work], [Program] 정도밖에 생각이 안나서, 이야기 해보고자 합니다.

**Comment by cnj8160** [comment]
네이밍이나 역할분배 등은 본격적으로 프로그래밍을 하기 전에 실시하는 사전작업이므로 [Setting], [Prior] 뭐 이런정도가 어떨까요?

**Comment by zanywhale** [comment]
Prior 괜찮은 것 같네요, 몇몇 이슈 작업들에도 적용시키도록 하겠습니다.

**Comment by zanywhale** [comment]
추가적인 Comment를 20일 자정까지 받고 해당 이슈는 Close 하겠습니다.
