### ISSUE TITLE
Checkpoint comment

### ISSUE THREAD

**Issue by sangkilc** [KAIST-IS521/2018s-onion-team3#40]
1. 열정적인 개발이 돋보입니다.
2. 하지만 @cnj8160 @skyshiri  학생은 contribution이 너무 부족해보입니다. 이 부분에 대한 분배를 어떻게 할지에 대해서는 좀 더 논의가 필요할 거 같습니다.
3. 세부 코멘트는 TA가 줄 예정 (@seongil-wi )

**Comment by 2dvorak** [comment]
유익한 피드백 감사드립니다!
개발 초기에는 역할 분배를 통해 진행하다가, 중반부터는 역할 분배가 잘 이루어지지 않은 것 같습니다. 하지만 @cnj8160 @skyshiri 두 분이 presentation(+영상)과 README를 맡아서 진행해주고 있기 때문에, 점점 contribution 균형을 맞출 수 있을 것 같습니다. 하지만 그와 별개로, 개발 부분에서도 최대한 균형을 맞출 수 있도록 하겠습니다.

다시 한번 피드백 감사드립니다 🚩

**Comment by 2dvorak** [comment]
팀원들 모두 코멘트를 숙지하였고, 앞으로의 진행 방향에 대한 논의가 이루어졌기 때문에 해당 이슈를 닫도록 하겠습니다. 감사합니다.
