### ISSUE TITLE
[Program] Queue, Vector 관리

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#42]
현재 Queue모델이 이상하게 적용되어 있어, 아무래도 수정이 불가피해보입니다.
저번에 @2dvorak 님과 대화를 나눠본 결과 Queue를 각자 githubID 별로 나눠야 할 것 같아요.
일단 제가 맡...게 될 것 같은데 아이디어 더 있으시면 주세요.

**Comment by 2dvorak** [comment]
네, 아무래도 큐이다 보니깐 모든 채팅방의 메시지를 하나의 큐로 관리하는게 문제가 됩니다.
그리고 무엇보다
```
일단 제가 맡...게 될 것 같은데
```
정말 좋은 아이디어입니다. 🙆‍♂️

**Comment by zanywhale** [comment]
@2dvorak 재미있는 부분이라 원하시면 드릴게요 ^_^

**Comment by zanywhale** [comment]
@2dvorak 이부분 하고싶어하셨으니 맡아주시면 감사히 맡기겠습니다.

**Comment by 2dvorak** [comment]
👎

**Comment by 2dvorak** [comment]
해당 이슈 브랜치에서 도커파일을 좀 수정했는데요.
README 작성에서 최대한 최신 버전의 메신저를 실행하실 수 있도록 머지하고 마저 작업하고자 합니다.
pr드립니당 컨플릭 날수도 있습니다 도커쪽에서..

**Comment by zanywhale** [comment]
넵넵 뭔가 오류가 있었던 것 같습니다. 머지 받은 부분들중에 문제가 됐던 Dockerfile과 setup.sh은 제가 조금 수정했고, 추가적으로 Dockerfile에서 컴파일이 되도록 변경해놨습니다!

**Comment by 2dvorak** [comment]
작업 속도가 더딘 것에 대한 변명을 하자면, 현재 queue를 vector로 바꾼건 되었는데, 문제는 UI 쓰레드 쪽에서 메시지를 찍어줄때인데요. 예전에는 UI에서 queue를 읽어와서 msgList를 만들면서 화면 크기에 맞게 메시지를 짤라서 줄바꿈을 처리했는데, 지금은 msgList가 send 소켓쪽에서 만들어지다 보니 화면 크기를 알지 못합니다. 따라서 출력시에 동적으로 줄바꿈 등의 작업을 처리해 주려고 하는데, 그러다 보니 루프를 얼마나 돌려야 될지 애매해지고 또 스크롤 등의 기능까지 더해지니 복잡해지고 있습니다.
현재 구상한 방법은 화면 크기 만큼의 스트링을 만들어 놓고 쓰려고 합니다. 화면이 바뀔 때마다 벡터를 가지고 노는 것보단 스트링을 가지고 노는게 빠를 거 같아서요..

**Comment by 2dvorak** [comment]
vector로 만들어주고 출력도 해결했는데, 이젠 메시지 송수신이 안되네요.

**Comment by zanywhale** [comment]
@_@ 어떻게 안되나요?

**Comment by 2dvorak** [comment]
>"안되면 되게하라" - @skyshiri  

푸시했습니다.

**Comment by 2dvorak** [comment]
문제점은 UI의 Send Thread에서 SetMessage를 호출 할 때 자신의 ID를 넣어주지 않고 상대방의 ID를 넣어줘서 받는 쪽에서 보낸이가 자기 자신으로 보이는 것에 있었습니다.
