### ISSUE TITLE
[Presentation] Presentation

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#43]
이번 onionMessenger에서 개발에 참여하기에 조금 제한되는 @cnj8160 님 께서는 모든 발표를 전적으로 맡아주시기로 했습니다.

물론 본 repo에서는 presentation을 다루지 않지만, 매번 저희가 개발하면서 체크하는 것 보단, 이슈를 하나 파두어 여기에 댓글로 진행사항이나 에로사항을 말씀해주시면 좋을 듯 싶습니다.

확인하고 Comment로 남겨주세요! 적어도 하루에 한 번 진행사항을 남겨주셨으면 합니다.

**Comment by cnj8160** [comment]
확인!!!!!!!@!@!!!!!
현재 동영상 편집 작업 중이며 각 scene들을 적절한 위치에 배치하는 1차 편집까지 완료 하였습니다
추후 자막+BGM 및 효과 추가하도록 하겠습니당

**Comment by zanywhale** [comment]
아 프리젠테이션에 저희 업무 분담 내용도 추가하면 좋을 것 같습니다.

**Comment by cnj8160** [comment]
Proposal 작성 때문에 오늘 진도를 많이 나가지 못했네요 ㅜㅜ
일단, 추가촬영분을 삽입하여 1차 편집본 수정하였습니다.
그런데 소리가 너무 작고 각각의 scene마다 밝기가 달라서 이 부분들 세세하게 조정해줘야 할 것 같습니다.
내일 위에 문제를 수정하고 본격적으로 gitpitch 틀 작성할 예정입니다.

**Comment by zanywhale** [comment]
조교님이 남겨주셨던 교수님의 코맨트입니다. 잊지말아주세요!
```
- 제품 이름?
- 제품에 대한 기술적 특장점?
- 제품에 대한 멤버들의 열정
```

**Comment by cnj8160** [comment]
구매자가 궁금할 수 있는 부분들을 질문하면 그에 대한 대답을 해주는 방식으로 PPT를 구성할까 하는데
우리가 구매자 입장이라면 어떤 점들이 궁금할까요?
ex. 굳이 이걸 써야 하나요? or 암호화가 되는 건가요? or 속도는 빠른가요? 등등

**Comment by zanywhale** [comment]
시연영상 외에 속도 측정 영상같은거 하나 추가하면 어떨까요?
3명이 있을 때, 4명 있을 때, 6명 있을 때, 시간 늘어나는거 보여주면서 지금 0.2초정도 걸리는데 그런거 보여주는거요!

**Comment by cnj8160** [comment]
좋은 생각입니다. "속도는 빠른가요?" 질문에 이어서 해당 영상 또는 gif 파일을 보여주면 좋겠네요.

**Comment by zanywhale** [comment]
아 그리고 6명 있을 때 중간에 어떻게 누구누구 거치는지 출력되게해서 동영상으로 보여주는것도 괜찮을 것 같아요. 그리고 이 영상 뒤에 이어서 전송된 메시지를 봤을 때 JSON간거 보여주고, 거기서 다 암호화되어있는것만 딱 보여주면 좋을 것 같아요

**Comment by cnj8160** [comment]
개인적으로는 그걸 실제 동영상으로 보여주는 것보다는 구매자들이 보기 좋도록, 귀여운 캐릭터들을 이용해서 누구누구를 거치는지 이미지로 나타내주는게 좋지 않을까 생각됩니다. 
먼저 실제 동작 화면을 캡쳐해서 보여주고 "여러분들의 이해를 돕기위해 이미지로 표현했습니다" 하면서 그 이미지를 보여주면 괜찮을것 같은데 어떠신가요?

그리고 최종 마무리를 위해서 오늘이나 내일 중 짧게나마 오프라인 모임을 한번 더 가졌으면 하는데
@zanywhale @2dvorak @skyshiri  다들 시간 괜찮으신가요?

**Comment by 2dvorak** [comment]
저녁시간 이후면 가능합니다! 좀따가 저녁을 나가서먹으라해가지궁...ㅠ
하는건 없지만 밥은 잘먹읍니다 ㅎㅎ
여유있게 8시 이후?정도가 좋을거같네요

**Comment by 2dvorak** [comment]
@zanywhale 누구누구 거치는지 출력?그럼 임의의 대화 모드를 해놓고 무조건 프린트 찍게 하는겁니꺄르륵?

**Comment by skyshiri** [comment]
저도 오늘 8시 이후로는 가능합니다.

**Comment by zanywhale** [comment]
저도 8시는 가능합니다
@2dvorak 대화모드 틀어놓고 프린터찍게하는거에용 저 디거빙할때처럼

**Comment by cnj8160** [comment]
그럼 오늘 8시에 비밀의방에서 뵙겠습니다!

**Comment by cnj8160** [comment]
방금 회의 했던 내용들을 토대로 gitpitch 대략적인 틀 만들도록 하겠습니다!

**Comment by zanywhale** [comment]
지금보니까 pitchme.md에도 readme.md가 있긴 하네요
최상단에 https://github.com/KAIST-IS521/2018s-onion-team3를 넣어 링크만 걸어주고,
나머지 내용들은 onion에 있는 Abstract라던가 Team member를 가져다가 쓰면 될 것 같습니다.

**Comment by cnj8160** [comment]
넵 알겠습니다!

**Comment by cnj8160** [comment]
https://github.com/KAIST-IS521/2018s-presentation-team3/tree/onion
이곳에 대략적인 발표틀을 만들어놨습니다.
어떤 순서로 발표할것인지 대강 틀만 잡은 것이기 때문에 추후 계속 수정해나갈 예정입니다.
표지에 "IS521 ONION MESSENGER ACTIVITY - TEAM HER"을 한 줄로 표현해놨는데
TEAM-HER을 아래로 내리니까 너무 화면이 조잡해 보여서 일단 저렇게 해놓았습니다.

발표와 관련된 의견들 부담없이 말씀해주시면 추후 반영하도록 하겠습니다.
일단은 동영상 작업부터 ㅜㅜ

**Comment by zanywhale** [comment]
제 Feedback입니다.

- 제목에 있는 WHY NOT?은 의미가 전달이 잘 안될 것 같습니다. ㅠㅠ 빼거나 다른 문구를 찾아보는건 어떨까요?
- IS521은 없어도 될 것 같습니다. 저번에 주신 피드백은 제목에 이게 뭐에 대한 PT이다라는 것에 대한 설명이 부족한 것에 대한 예시였으니, ONION MESSENGER ACTIVITY - TEAM HER만 들어가도 문제 없을 것 같습니다.
- Question1에는 아마 사진과 명령어를 넣으 실 것 같은데, 도커만 설치하면 ./startMessenger 하나로 실행되는거 보여주면 될 것 같아요
- Question2에 들어가는 영상 제가 드린거 Randompath제대로 적용 안된 버전같아요.. 그거 다시 직어서 드리던가 할게요!
- Question3 GPGME는 Selling하는 부분 말고 뒤에 우리 얘기 쓸때 어려웟던 점이라던가 할때 쓰는건 어떨까요? 앞에서는 빠른 서비스를 제공한다. 정도면 될 것 같습니다.
- 기타에 스크롤은 gif이미지 첨부하는게 좋을 것 같아요. 하나 맹글어드릴게요
- 팀원 열정 부분에 우리 Issue로 서로 오가면서 대화한 내용들을 넣으면 좋을 것 같아요. 우리가 이렇게 대화한 내용들이 실제로 구현되었다 라던가 이런 이슈들사진이 한 2~3개, 슬라이드 2장~3장 써도 괜찮으니글씨 보일 정도의 크기로 넣으면 좋을 것 같습니다.
- 그리고 팀원 열정에 전체 커밋수 보여주는것도 좋을 것 같습니다. 많이 열심히 했다는거니까요.
- 교수님이 보고싶어하시는 제품 이름이 안들어가있습니다. HER Messenger을 넣어주면 좋을 것 같습니다. 개인적인 생각으로는 HER이 컬링에서 빨리 닦으라고 했던 우리 말처럼, 메시지가 매우 빨리 전송되는 암호화된 메신저라고 꿈보다 해몽을 달아보는게 어떨까요?ㅎㅎ
- 실제 구현 내용에 대한 설명이 들어가야 할 것 같습니다. 전체적인 구성은 괜찮은 것 같아요. Selling파트가 끝나면 실제 뒤에는 구현내용 (프로토콜같은..)것들이 들어가야 할 것 같습니다. Selling이긴하지만, 우리가 만든 것에 대한 설명이 필요하긴 하니까요.
- 시연이 필요 할 것 같습니다. 시연 환경은 제가 랩실 컴에 구성해놓고 가겠습니다. 발표 전에 켜놓고 최소화 해둔 뒤, 시연 차례가 오면 Alt+Tab , 시연을 하면 될 것 같습니다.

일단 생각나는건 이 정도 입니다. 위 내용은 제가 생각하기에 꼭 필요한 내용들이라, 만약 이해가 안가시거나 아니다싶은것 있으면 comment달아서 알려주세요!

**Comment by cnj8160** [comment]
- 제목 고민해보겠습니다.
- IS521 제거하겠습니다.
- ./startMessenger 하나로 실행되는거 보여주겠습니다
- 네 나중에 다시 찍어서 보내주세요~
- 그럼 확실하게 앞부분은 Selling 파트고 뒷부분은 For class 파트인걸 명시하고 GPGME는 뒷부분으로 보내겠습니다.
- 스크롤 gif 굳굳
- 팀원 열정에 이슈+커밋수 등등 보여주는거 좋네요!
- 제품이름 등에 대한 설명은 "프로그램 동작과정"파트에 프로그램 첫화면 캡쳐와 함께 보여주려고 했었습니다. 원래는 이곳에 실제로 프로그램을 실행시켜 로그인을 하고 채팅을 하는 과정을 영상으로 첨부하려고 했었는데 뒷부분에 실제 시연을 한다면 이 영상은 필요 없을 것 같습니다.
- 구현내용 뒷부분에 추가 하겠습니다.

**Comment by zanywhale** [comment]
물론 열정이나 이런걸 Selling에 녹이는 방식도 나쁘지 않아 보이는데, 시나리오가 굉장히 까다로워질것같아서요 ㅠㅠ

**Comment by cnj8160** [comment]
동영상 2차편집 완료하였습니다.
토요일 중으로 자막 + BGM 작업까지 모두 완료될 것 같은데 그 후에 본격적으로 GitPitch 작업 시작하도록 하겠습니다.

**Comment by cnj8160** [comment]
동영상 작업 모두 완료하여 유투브에 '미등록' 상태로 업로드 하였습니다

**Comment by 2dvorak** [comment]
😃🔫

**Comment by zanywhale** [comment]
😃🔫

**Comment by cnj8160** [comment]
발표가 끝났으므로 해당 이슈는 닫겠습니다!!!
