### ISSUE TITLE
[Prior] Development Environment & Naming Convention

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#5]
- 개발을 나누어서 해야하는 환경이라, 다음과 같이 개발 환경을 맞추도록 하겠습니다.
```
- Docker
- Qt Creator
```

- 다음과 같은 Naming Convention을 사용하도록 하겠습니다.
```
- Class선언 시 대문자로 시작
- 변수 선언 시 소문자로 시작
- 함수 선언 시 대문자로 시작
- Camel Case
```

이견이나 추가되어야 하는 의견 있으시면 답글 달아주세요.
해당 이슈는 19일 6시 까지 유효합니다.

**Comment by zanywhale** [comment]
추가적으로, 앞으로 모든 커밋에는 서명을 넣어주세요!

**Comment by zanywhale** [comment]
19일 6시가 지났습니다. 해당 컨밴션은 계속 쓸 예정이니 염두해두시길 바랍니다.

**Comment by 2dvorak** [comment]
```
- 함수 선언 시 대문자로 시작
```
으아ㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏ
