### ISSUE TITLE
[Program] 소켓 버퍼 길이 처리, 특수문자, 패딩

### ISSUE THREAD

**Issue by 2dvorak** [KAIST-IS521/2018s-onion-team3#53]
현재 소켓 버퍼가 4096바이트로 한정되어 있습니다. 따라서 메시지의 길이에 따라 유동적으로 읽어들일 수 있는 버퍼로 바꾸어 봅시다.
탭, 줄바꿈 등의 특수문자를 처리하지 못합니다. 특히 줄바꿈에 대해 고민해 봅니다.
경유지에서 랜덤 패딩을 붙여 봅시다. 물론 소켓 버퍼를 해결해주지 않으면 재미난 광경이 펼쳐지겠죠.

**Comment by 2dvorak** [comment]
브랜치 이름을 뭐로 해야되나.

**Comment by 2dvorak** [comment]
호호호.. read()를 잘게 나누어서 루프를 돌렸더니 중간에 끊기는 현상이 있습니다.

**Comment by 2dvorak** [comment]
timeout?그런거 때문인가 싶어서 setsocketopt로 타임아웃 좀 늘려보고, select 이런거도 써보고(사실 뭔지 잘 모름) 이것저것 해봤는데 잘 안됩니다요. read가 중간에 끊겨서 JSON에서 터지거나, read가 전부 다 된거같으면(안터지면) 1. list에서 안보입니다.

**Comment by 2dvorak** [comment]
보내는 쪽에서도 쪼개서 보내면 어떨까 하는 생각이 드네요

**Comment by 2dvorak** [comment]
그런거랑 상관없이 쪼개서 받는 경우에는 도무지 list를 못만드네요.

**Comment by 2dvorak** [comment]
어쩌다 되었는지는 모르겠지만 키 교환했어요. 지금은 일단 4096바이트씩 읽어서 ```\"}```문자열 찾아본다음에 있으면 처리하는..그딴식입니다. 이제 제대로 되는지 시험하기 위해 4096 바이트를 넘겨봐야겠죠. 패딩 만들러 갑니다.

**Comment by 2dvorak** [comment]
네 패딩도 했고요. 특수문자는 일단 탭만 처리하겠슴다.. 줄바꿈은 입력하기 위한 엔터와 어떻게 구분해야될지.. 까다롭네요.

**Comment by zanywhale** [comment]
줄바꿈은 굳이 필요없는 부가기능 같습니다. 그거 버리고 지금까지 한거에서 차라리 발전시킬 수 있는 쪽으로 발전시키는게 나아보입니다~~~
