### ISSUE TITLE
[Program] 마지막 기능 추가

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#55]
찐막 기능 추가입니다.
리스트에서 나오는 명단에 몇개의 메시지가 와있는지 확인하는 기능이 필요합니다.
ex) githubA (3)
     githubB (0)
     githubC (10)

**Comment by 2dvorak** [comment]
>자 떠나자 동해바다로 삼등삼등 완행열차 기차를 타고
>-송창식, 고래사냥 중

**Comment by cnj8160** [comment]
ㄹㅇ 바로 팔아도 될듯

**Comment by 2dvorak** [comment]
찐막기능 추가요
