### ISSUE TITLE
dos attack using talk function

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-onion-team3#67]
I can attack target client by sending message rapidly.
![peek 2018-04-09 19-17](https://user-images.githubusercontent.com/36834930/38492690-c4ee9458-3c2a-11e8-9611-cacf689d5d30.gif)

**Comment by zanywhale** [comment]
Oh... I thought we had fixed this problem, but it still happens.
@_@! 
@2dvorak

**Comment by 2dvorak** [comment]
Working on it, sorry @zanywhale  😄🔫

**Comment by 2dvorak** [comment]
@sunnyeo thank you for your reports. If it's possible, can you try your rapid typing one more time? I updated the code in master branch to patch this bug, hopefully.
