### ISSUE TITLE
[Presentation] Prepare presentation

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#7]
최종 발표때 사용될 프리젠테이션 제작이 필요합니다.
Issue #1 을 기준으로 프리젠테이션 구상을 하면 될 것 같습니다.

**Comment by skyshiri** [comment]
제가 생각해본 발표 방향입니다.

Who is our target? 
메신저가 사용하기는 쉽지만, 해킹이 어렵고 익명성이 보장되길 원하는 모든 사람

design of the protocol
1. Message Protocol (그림파일)
2. Key Protocol (그림파일) 

우리 메신저의 장점은? (동영상 촬영) 
1. 사용하기 쉽다. 
2. 익명성이 철저히 보장된다.
    - 이런 암호기법 사용해서 슈퍼컴퓨터로도 몇년 걸린다??
3. 사진파일, 영상파일을 보낼 수 있다? 
4. 이모티콘 전송 가능?
    * 3, 4번은 구현이 어렵겠죠?

**Comment by zanywhale** [comment]
3. 사진파일까지는 보낼 수 있을 것 같은데, 저한테 아이디어가 있으니 일단 넘어가고, 이모티콘은 조금 힘들 것 같아요ㅠㅠ

그리고 아마 시연을 하는 단계가 있지 않을까싶네요!

**Comment by zanywhale** [comment]
해당 이슈는 본 개발 repo와 목적에 맞지 않기 때문에 close하겠습니다.
gitpitch및 브리젠테이션 작업은 전부 presentation repo에서 진행하겠습니다.
