### ISSUE TITLE
Resource Leak (heap memory leck) 

### ISSUE THREAD

**Issue by k1rh4** [KAIST-IS521/2018s-onion-team3#70]
you used a lot of heap memory when you have just a message.
but there is no free heap memory.

your messenger will got abort error. If you have a lot of messege even though that is a client messeges. 
because heap memory allocation defend on TOP chunk size. 

you suppose to free when you finish recv data.

![heapmemoryleck](https://user-images.githubusercontent.com/26647718/38596524-f74c76aa-3d8c-11e8-80c3-7f44617896c3.PNG)

**Comment by zanywhale** [comment]
Yap! That's correct!
Thank you for finding the bug!
:)
