### ISSUE TITLE
[Presentation] Presentation CSS

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#8]
Presentation은 gitpitch로 진행 될 예정이고, CSS는 이전에 사용하던 BlackBinary를 적용 할 예정입니다.
이견이 있으시다면 Comments남겨주세요!

Gitpitch작업은 다른 분께 부탁드리겠습니다.

**Comment by zanywhale** [comment]
@skyshiri 이번 Presentation CSS 작업을 맡아주세요.

**Comment by skyshiri** [comment]
네, 알겠습니다.

**Comment by zanywhale** [comment]
PR 받았습니다. 해당 Issue 를 close하겠습니다.
