### ISSUE TITLE
[Program] Message protocol 설계

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team3#9]
해당 부분은 이전에 오프라인 모임 때 서로 이야기 된 부분이 아니기 때문에 이렇게 따로 issue를 팠습니다.
본 Issue에서는 Message Procotol에 대해서 다룰 예정입니다.

다 같이 Message Protocol에 대해서 생각해보도록 합시다.

**Comment by zanywhale** [comment]
- Message Protocol
- Key Protocol
정도만 해결되면 될 것 같네요.

Encrypt -> Decrypt했을 때 나오는 메시지로 파악하는 걸로 합시다. TCP 위에 태워서 전송하는걸로 하고.
전송은 굳이 몇 byte씩 필드를 나누는게 무의미할 수 있음. 일단 이메일, github id가 가변인자에 속하고 굳이 이 가변인자를 맞춰주기 위해 필드 낭비를 할 필요는 없음
따라서 모든 프로토콜은 JSON으로 오가는걸로 하는게 어떨까요?

기본적으로 Message와 Key를 가릴 수 있는 ID 영역
```
Message Protocol
Message에서 종착역인지, 아닌지를 알 수 있는 0 or 1에 관련된 필드
Message에서 다음으로 Send해야 할 IP 주소 필드
Message에서 주고 받은 사람의 Github ID 필드
```

```
Key Protocol
Key 요청, 오고 가는 것만 있으면 됌, Still alive의 목적을 가지고 있음
Key에서 요청인지, 답변인지에 대한 필드
Key에서 보낸이의 ID, pubkey를 항상 같이 전송(IP는 어차피 Sender의 IPaddr을 따오면 됌)
--- 결국 요청과 답변이 동일함
Key Protocol 상 더 이상 보낼 정보가 없어보임(있으면 추가 comment로 알려주세요
```

**Comment by 2dvorak** [comment]
c++ json 라이브러리를 사용하면 되겠네요.
그런데 id나 pubkey를 보내는 건 json이 좋겠지만 0/1만 필요한 필드들은 바이트로 박아넣는 게 더 빠를수도 있을 것 같고 데이터 길이를 줄일 수 있을 거 같아요.

**Comment by 2dvorak** [comment]
pubkey를 key protocol에 포함시킬지도 생각해볼수 있을 것인데, 교수님께서 Github 아이디를 사용하는 이유 중 하나가 지난 activity에서 학생들이 각자 올린 pubkey를 받아갈 수 있게 하기 위함이라고 하셨습니다.(꼭 그렇게 할 필요는 없다고 하셨지만) 하지만 깃헙에서 직접 키를 받거나, 키서버를 이용하는 것보다 직접 소켓으로 보내주는게 더 빠를 것 같네요.

**Comment by 2dvorak** [comment]
대신 모든 Key Protocol마다 pubkey를 보내지 말고, 저장해놓고 쓰는 방법도 있을 것 같아요. 그런데 pubkey를 자주 업데이트 할 필요가 있나요? 업데이트가 필요할 때만 키를 다시 보내주는 방법이 있을 것 같습니다. 그를 제외한 대부분의 Key Protocol은 IP와 Github ID로 생존신고만 하는거죠.

**Comment by 2dvorak** [comment]
그리고 맨 첨에 노드가 생기거나 없어질 때 broadcast? 처럼 하려면 다른 프로토콜을 써야 할까요?

**Comment by zanywhale** [comment]
1. 넵 C++에 있는 라이브러리를 사용 하면 될 것 같네요. 아니면 더 편한 오픈소스를 찾아도..
2. 0/1 필요한 바이트 따로, id,Pubkey따로 형식을 달리해서 사용하면 조금 복잡할 수 있다는 생각이 들어서요. 그리고 어차피 파싱만 하면되는 상황이라 JSON을 꼭 쓰지 않더라도 문제 없습니다 \r\d같은걸로 해도..
3. 흠... 고민해 볼 만한 내용이네요. 처음에는 pubkey가 필요하지만, 내 list에서 관리되고 있는 노드들은 전부 key가 있으니 Alive만 확인하는 상황에서는 괜한 네트워크 오버헤드가 될 수 있겠네요.
4. Broadcast는 다른 프로토콜이라기보단 지금 구성되어있는 스레드를 활용하여 Client Init에서 while 때려버리면 될 것 같습니다. 어차피 종료에 관련된건 내 list에서 관리되고 있는 애들만 뿌려주면 되니까, 굳이 BroadCast에 대한 프로토콜을 따로 작성하는건 필요 없을 것 같아요.

프로토콜이 많아질수록 설계가 복잡해지고, 프로토콜이 많으면 많을 수록 취약점이 많아질 확률도 높아진다고 생각해서 저는 프로토콜을 최소한으로 동작 가능하게 설계하려고 구상중에 있어서 많이 줄이려다보니 문제들이 조금씩 있기는 하네요 그 부분에 대해서는 조금 더 생각해 보도록 합시다!

**Comment by zanywhale** [comment]
아 그리고 이건 추가적인 보안 구현인데, 네트워크를 타고 가면 갈 수록 Size가 작아진다는 점을 착안하여 공격이 될 수 있다고 생각합니다. 이 부분을 Input -> Output으로 나갈 때 padding을 붙여 암호화 해 비슷한 크기로 만들어버리면, 최종 목표 지점을 이런 공격으로 알아내기는 쉽지 않을 것 같아요.

일단 구상중인 내용이고, Prototype이 만들어지고 난 이후에 추가하도록 합시다!

**Comment by zanywhale** [comment]
프로토콜 적용이 완료되었습니다.
해당 이슈를 닫도록 하겠습니다.
